services:
  # API Gateway
  - type: web
    name: canvas-cameo-gateway
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 10000  # Must use Render's default port
      - key: DESIGN_SERVICE_URL
        value: http://canvas-cameo-design:10000  # Private network DNS
      - key: UPLOAD_SERVICE_URL
        value: http://canvas-cameo-upload:10000
      - key: SUBSCRIPTION_SERVICE_URL
        value: http://canvas-cameo-subscription:10000
      - key: FRONTEND_URL
        value: https://canvas-cameo.vercel.app

  # Microservices (all use same port)

  # Design Service
  - type: web
    name: canvas-cameo-design
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        generateValue: true

  # Subscription Service

      - type: web
        name: canvas-cameo-subscription
        env: node
        plan: free
        buildCommand: npm install
        startCommand: node src/server.js
        envVars:
          - key: PORT
            value: 10000
          - key: MONGODB_URI
            generateValue: true

      # Upload Service

      - type: web
        name: canvas-cameo-upload
        env: node
        plan: free
        buildCommand: npm install
        startCommand: node src/server.js
        envVars:
          - key: PORT
            value: 10000
          - key: MONGODB_URI
            generateValue: true